import { AnnouncementPreset, LanguageInfo } from '../types';

export const LANGUAGES_CONFIG: LanguageInfo[] = [
  {
    code: 'vi',
    name: 'Tiếng Việt',
    nativeName: 'Tiếng Việt',
    flag: '🇻🇳',
    defaultVoice: 'Kore',
    defaultSpeed: 1.0,
    defaultPitch: 0,
    voiceOptions: [
      // Giọng Nữ
      { id: 'Kore', name: 'Kore - Nữ ấm áp, truyền cảm, chuẩn phát thanh', gender: 'Nữ', style: 'Truyền cảm, đón tiếp nồng hậu, chuẩn mực' },
      { id: 'Zephyr', name: 'Zephyr - Nữ trong trẻo, thanh lịch, tươi vui', gender: 'Nữ', style: 'Thanh lịch, trẻ trung, tự nhiên' },
      { id: 'Aoede', name: 'Aoede - Nữ duyên dáng, diễn cảm tự nhiên', gender: 'Nữ', style: 'Tự nhiên như đàm thoại trực tiếp, gần gũi' },
      { id: 'Leda', name: 'Leda - Nữ trẻ trung, ngọt ngào, dịu dàng', gender: 'Nữ', style: 'Ngọt ngào, nhẹ nhàng, du lịch khám phá' },
      { id: 'Despina', name: 'Despina - Nữ êm dịu, mượt mà, hiếu khách', gender: 'Nữ', style: 'Mượt mà, êm ái, tiếp đón khách VIP' },
      { id: 'Callirrhoe', name: 'Callirrhoe - Nữ tự tin, hiện đại, trang nhã', gender: 'Nữ', style: 'Thanh thoát, hiện đại, phong thái resort' },
      { id: 'Sulafat', name: 'Sulafat - Nữ sang trọng, đĩnh đạc, quý phái', gender: 'Nữ', style: 'Quý phái, trang trọng, thông báo gala' },
      { id: 'Erinome', name: 'Erinome - Nữ rõ ràng, dứt khoát, chuẩn xác', gender: 'Nữ', style: 'Rõ ràng, lưu loát, hướng dẫn quy định' },
      // Giọng Nam
      { id: 'Puck', name: 'Puck - Nam trầm ấm, lịch lãm, thân thiện', gender: 'Nam', style: 'Trầm ấm, rõ nét, trang trọng, gần gũi' },
      { id: 'Fenrir', name: 'Fenrir - Nam dõng dạc, mạnh mẽ, vang dội', gender: 'Nam', style: 'Dõng dạc, uy lực, thông báo an toàn/loa ngoài trời' },
      { id: 'Charon', name: 'Charon - Nam điềm đạm, chuẩn mực, chững chạc', gender: 'Nam', style: 'Điềm đạm, phong thái phát thanh viên tin tức' },
      { id: 'Orus', name: 'Orus - Nam trầm tĩnh, chắc chắn, tin cậy', gender: 'Nam', style: 'Vững chãi, đáng tin, thông báo hành trình' },
      { id: 'Alnilam', name: 'Alnilam - Nam hào sảng, dứt khoát, năng lượng', gender: 'Nam', style: 'Năng nổ, dứt khoát, sự kiện & lễ hội' },
      { id: 'Enceladus', name: 'Enceladus - Nam trầm ấm, sâu lắng, thư thái', gender: 'Nam', style: 'Sâu lắng, ấm cúng, thư giãn' },
      { id: 'Sadaltager', name: 'Sadaltager - Nam ân cần, tri thức, hướng dẫn viên', gender: 'Nam', style: 'Thân thiện, giải thích chỉ dẫn tỉ mỉ' },
      { id: 'Zubenelgenubi', name: 'Zubenelgenubi - Nam trầm vang, phong thái đài phát thanh', gender: 'Nam', style: 'Âm vang cổ điển, phong thái đài phát thanh lớn' },
    ],
  },
  {
    code: 'en',
    name: 'Tiếng Anh',
    nativeName: 'English',
    flag: '🇬🇧',
    defaultVoice: 'Kore',
    defaultSpeed: 1.0,
    defaultPitch: 0,
    voiceOptions: [
      // Female
      { id: 'Kore', name: 'Kore - Female: Warm, welcoming & articulate', gender: 'Nữ', style: 'Warm hospitality, articulate resort tone' },
      { id: 'Zephyr', name: 'Zephyr - Female: Bright, crisp & modern', gender: 'Nữ', style: 'Gentle, modern, crisp pronunciation' },
      { id: 'Aoede', name: 'Aoede - Female: Breezy, natural & engaging', gender: 'Nữ', style: 'Conversational, natural and smooth' },
      { id: 'Leda', name: 'Leda - Female: Youthful, sweet & gentle', gender: 'Nữ', style: 'Sweet, pleasant travel announcements' },
      { id: 'Despina', name: 'Despina - Female: Smooth, warm & hospitable', gender: 'Nữ', style: 'Smooth, welcoming, VIP hospitality' },
      { id: 'Callirrhoe', name: 'Callirrhoe - Female: Confident & graceful', gender: 'Nữ', style: 'Polished, confident, international resort tone' },
      { id: 'Sulafat', name: 'Sulafat - Female: Sophisticated & grand', gender: 'Nữ', style: 'Formal, luxurious, grand event announcements' },
      { id: 'Erinome', name: 'Erinome - Female: Clear, articulate & precise', gender: 'Nữ', style: 'Crisp diction, guidelines & regulations' },
      // Male
      { id: 'Puck', name: 'Puck - Male: Polished, friendly & confident', gender: 'Nam', style: 'Deep, friendly international standard' },
      { id: 'Fenrir', name: 'Fenrir - Male: Commanding, dynamic & authoritative', gender: 'Nam', style: 'Commanding outdoor broadcast, safety notice' },
      { id: 'Charon', name: 'Charon - Male: Calm, formal & professional', gender: 'Nam', style: 'News anchor composure, professional delivery' },
      { id: 'Orus', name: 'Orus - Male: Firm, reassuring & reliable', gender: 'Nam', style: 'Steady, reliable travel information' },
      { id: 'Alnilam', name: 'Alnilam - Male: Vibrant, energetic & bold', gender: 'Nam', style: 'Upbeat festival & show announcements' },
      { id: 'Enceladus', name: 'Enceladus - Male: Deep, calm & soothing', gender: 'Nam', style: 'Relaxing, warm evening tone' },
      { id: 'Sadaltager', name: 'Sadaltager - Male: Courteous, knowledgeable guide', gender: 'Nam', style: 'Tour guide style, friendly instructions' },
      { id: 'Zubenelgenubi', name: 'Zubenelgenubi - Male: Deep resonance, radio station tone', gender: 'Nam', style: 'Rich resonant voice, classic public PA' },
    ],
  },
  {
    code: 'ko',
    name: 'Tiếng Hàn',
    nativeName: '한국어',
    flag: '🇰🇷',
    defaultVoice: 'Zephyr',
    defaultSpeed: 1.0,
    defaultPitch: 0,
    voiceOptions: [
      // 여성
      { id: 'Zephyr', name: 'Zephyr - 여성: 다정하고 정중한 안내', gender: 'Nữ', style: '정중한 테마파크 방송 톤' },
      { id: 'Kore', name: 'Kore - 여성: 차분하고 품격 있는 톤', gender: 'Nữ', style: '차분하고 품격 있는 안내' },
      { id: 'Aoede', name: 'Aoede - 여성: 자연스럽고 생생한 발음', gender: 'Nữ', style: '자연스러운 대화형 나레이션' },
      { id: 'Leda', name: 'Leda - 여성: 밝고 상냥한 목소리', gender: 'Nữ', style: '밝고 상냥한 관광 가이드' },
      { id: 'Despina', name: 'Despina - 여성: 부드럽고 따뜻한 음색', gender: 'Nữ', style: '호텔 및 VIP 라운지 안내' },
      { id: 'Callirrhoe', name: 'Callirrhoe - 여성: 세련되고 깔끔한 톤', gender: 'Nữ', style: '현대적이고 명확한 방송' },
      { id: 'Sulafat', name: 'Sulafat - 여성: 격조 높고 우아한 목소리', gender: 'Nữ', style: '공식 행사 및 갈라 쇼' },
      { id: 'Erinome', name: 'Erinome - 여성: 또박또박하고 명확한 발음', gender: 'Nữ', style: '안전 수칙 및 규정 안내' },
      // 남성
      { id: 'Puck', name: 'Puck - 남성: 부드럽고 든든한 톤', gender: 'Nam', style: '부드러운 남성 안내 방송' },
      { id: 'Fenrir', name: 'Fenrir - 남성: 웅장하고 힘찬 안내', gender: 'Nam', style: '야외 확성 및 안전 방송' },
      { id: 'Charon', name: 'Charon - 남성: 신뢰감 있는 아나운서 톤', gender: 'Nam', style: '차분한 공식 뉴스/안내' },
      { id: 'Orus', name: 'Orus - 남성: 묵직하고 안정된 음색', gender: 'Nam', style: '신뢰감 있는 시설 안내' },
      { id: 'Alnilam', name: 'Alnilam - 남성: 활기차고 경쾌한 톤', gender: 'Nam', style: '축제 및 이벤트 공지' },
      { id: 'Enceladus', name: 'Enceladus - 남성: 차분하고 편안한 톤', gender: 'Nam', style: '야간 힐링 및 테마 안내' },
      { id: 'Sadaltager', name: 'Sadaltager - 남성: 친절하고 지적인 가이드', gender: 'Nam', style: '친절한 관광 안내' },
      { id: 'Zubenelgenubi', name: 'Zubenelgenubi - 남성: 깊은 울림의 클래식 라디오', gender: 'Nam', style: '중후하고 깊은 방송 톤' },
    ],
  },
  {
    code: 'zh',
    name: 'Tiếng Trung',
    nativeName: '中文',
    flag: '🇨🇳',
    defaultVoice: 'Kore',
    defaultSpeed: 1.0,
    defaultPitch: 0,
    voiceOptions: [
      // 女性
      { id: 'Kore', name: 'Kore - 女性: 亲切标准播音腔', gender: 'Nữ', style: '典雅亲切，标准普通话' },
      { id: 'Zephyr', name: 'Zephyr - 女性: 甜美清澈导览', gender: 'Nữ', style: '甜美自然，适合景区公告' },
      { id: 'Aoede', name: 'Aoede - 女性: 灵动自然，娓娓道来', gender: 'Nữ', style: '自然亲切，生动讲述' },
      { id: 'Leda', name: 'Leda - 女性: 青春柔美，轻快活力', gender: 'Nữ', style: '年轻轻快，旅游指引' },
      { id: 'Despina', name: 'Despina - 女性: 温婉柔和，宾至如归', gender: 'Nữ', style: '温润舒适，贵宾礼遇' },
      { id: 'Callirrhoe', name: 'Callirrhoe - 女性: 优雅自信，干练大方', gender: 'Nữ', style: '国际度假区现代播音' },
      { id: 'Sulafat', name: 'Sulafat - 女性: 庄重大气，贵宾盛典', gender: 'Nữ', style: '大型晚会及正式播报' },
      { id: 'Erinome', name: 'Erinome - 女性: 字正腔圆，清晰严谨', gender: 'Nữ', style: '规则指引与安全注意事项' },
      // 男性
      { id: 'Puck', name: 'Puck - 男性: 浑厚沉稳，专业庄重', gender: 'Nam', style: '浑厚沉稳，专业庄重' },
      { id: 'Fenrir', name: 'Fenrir - 男性: 嘹亮有力，指令明确', gender: 'Nam', style: '户外大喇叭安全通知' },
      { id: 'Charon', name: 'Charon - 男性: 从容端庄，新闻主播', gender: 'Nam', style: '沉着冷静，标准播音员' },
      { id: 'Orus', name: 'Orus - 男性: 刚健可靠，诚恳稳重', gender: 'Nam', style: '稳健指引，旅程播报' },
      { id: 'Alnilam', name: 'Alnilam - 男性: 热情激昂，盛典欢庆', gender: 'Nam', style: '游园演出与节日开场' },
      { id: 'Enceladus', name: 'Enceladus - 男性: 舒缓温暖，亲切磁性', gender: 'Nam', style: '夜间漫步与舒缓提醒' },
      { id: 'Sadaltager', name: 'Sadaltager - 男性: 儒雅细致，金牌导览', gender: 'Nam', style: '导游解说与贴心提示' },
      { id: 'Zubenelgenubi', name: 'Zubenelgenubi - 男性: 低沉共鸣，经典广播', gender: 'Nam', style: '深沉醇厚，经典公共广播' },
    ],
  },
  {
    code: 'ru',
    name: 'Tiếng Nga',
    nativeName: 'Русский',
    flag: '🇷🇺',
    defaultVoice: 'Kore',
    defaultSpeed: 1.0,
    defaultPitch: 0,
    voiceOptions: [
      // Женский
      { id: 'Kore', name: 'Kore - Женский: Приятный и четкий диктор', gender: 'Nữ', style: 'Вежливый тон курортного диктора' },
      { id: 'Zephyr', name: 'Zephyr - Женский: Мягкий доброжелательный', gender: 'Nữ', style: 'Мягкая подача для туристов' },
      { id: 'Aoede', name: 'Aoede - Женский: Естественный и живой голос', gender: 'Nữ', style: 'Приятная разговорная интонация' },
      { id: 'Leda', name: 'Leda - Женский: Юный, легкий и теплый', gender: 'Nữ', style: 'Свежий тон для экскурсий' },
      { id: 'Despina', name: 'Despina - Женский: Бархатистый и гостеприимный', gender: 'Nữ', style: 'Гостеприимный тон отеля и VIP' },
      { id: 'Callirrhoe', name: 'Callirrhoe - Женский: Уверенный и элегантный', gender: 'Nữ', style: 'Современный международный стиль' },
      { id: 'Sulafat', name: 'Sulafat - Женский: Торжественный и представительный', gender: 'Nữ', style: 'Для торжеств и гала-программ' },
      { id: 'Erinome', name: 'Erinome - Женский: Четкий, артикулированный', gender: 'Nữ', style: 'Инструкции и техника безопасности' },
      // Мужской
      { id: 'Puck', name: 'Puck - Мужской: Спокойный, солидный голос', gender: 'Nam', style: 'Спокойный, солидный голос' },
      { id: 'Fenrir', name: 'Fenrir - Мужской: Громкий, командный, четкий', gender: 'Nam', style: 'Уведомления о безопасности' },
      { id: 'Charon', name: 'Charon - Мужской: Сдержанный диктор новостей', gender: 'Nam', style: 'Официальные информационные объявления' },
      { id: 'Orus', name: 'Orus - Мужской: Надежный, твердый и спокойный', gender: 'Nam', style: 'Надежный информационный голос' },
      { id: 'Alnilam', name: 'Alnilam - Мужской: Энергичный, праздничный', gender: 'Nam', style: 'Анонсы шоу и праздников' },
      { id: 'Enceladus', name: 'Enceladus - Мужской: Мягкий, глубокий баритон', gender: 'Nam', style: 'Уютный вечерний тон' },
      { id: 'Sadaltager', name: 'Sadaltager - Мужской: Приветливый экскурсовод', gender: 'Nam', style: 'Гид и подробные указания' },
      { id: 'Zubenelgenubi', name: 'Zubenelgenubi - Мужской: Глубокий радио-бас', gender: 'Nam', style: 'Классическое радиовещание' },
    ],
  },
];

export const PRESET_ANNOUNCEMENTS: AnnouncementPreset[] = [
  {
    id: 'event-start-15min',
    title: 'Thông báo sự kiện / Chương trình biểu diễn sắp bắt đầu (15 phút)',
    category: 'show',
    categoryLabel: 'Sự Kiện & Biểu Diễn',
    location: 'Khu vực khán đài & Sân khấu chính',
    tone: 'energetic',
    scripts: {
      vi: 'Kính thưa quý khách, chương trình biểu diễn nghệ thuật đặc sắc sẽ chính thức bắt đầu sau 15 phút nữa tại khu vực sân khấu chính. Xin mời quý khách vui lòng ổn định chỗ ngồi và sẵn sàng thưởng thức màn trình diễn âm thanh và ánh sáng đặc biệt. Chúc quý khách một buổi tối tràn ngập niềm vui!',
      en: 'Ladies and gentlemen, our special live performance show will begin in 15 minutes at the main stage area. Please kindly take your seats and get ready to enjoy an extraordinary spectacle of music and light. We wish you an unforgettable evening!',
      ko: '방문객 여러분 안녕하십니까. 메인 무대에서 펼쳐지는 특별 공연이 15분 후 시작될 예정입니다. 관람을 원하시는 고객께서는 좌석에 착석해 주시기 바랍니다. 즐거운 관람 되시기 바랍니다. 감사합니다.',
      zh: '尊敬的各位观众，精彩的艺术表演大秀将在15分钟后于主舞台正式开演。请各位观众尽快入座，静候这场美妙的视听盛宴。祝您度过一个愉快的夜晚！',
      ru: 'Уважаемые дамы и господа! Специальная шоу-программа начнется через 15 минут на главной сцене. Просим вас занять свои места и приготовиться к незабываемому представлению. Желаем приятного отдыха!',
    },
  },
  {
    id: 'venue-safety-guideline',
    title: 'Thông báo an toàn và hướng dẫn tham quan',
    category: 'kiss_bridge',
    categoryLabel: 'An Toàn & Hướng Dẫn',
    location: 'Toàn bộ khuôn viên tham quan',
    tone: 'gentle',
    scripts: {
      vi: 'Kính thưa quý khách, để đảm bảo an toàn và giữ gìn cảnh quan chung, xin quý khách lưu ý đi theo các lối đi chỉ dẫn, không tựa người hoặc leo trèo qua các lan can bảo vệ và cẩn thận giữ gìn tư trang cá nhân. Xin chân thành cảm ơn sự hợp tác của quý khách!',
      en: 'Ladies and gentlemen, for your safety and comfort, please stay on the designated paths, do not lean over or climb safety railings, and keep a close eye on your personal belongings. Thank you for your kind cooperation!',
      ko: '방문객 여러분 안녕하십니까. 안전하고 쾌적한 관람을 위해 지정된 이동 경로를 이용해 주시고 안전 난간에 기대거나 올라가지 마시기 바랍니다. 소지품 보관에도 각별히 유의해 주시기 바랍니다. 감사합니다.',
      zh: '各位游客朋友们，为了您的安全与舒适体验，请在指定游览通道内行走，切勿倚靠或攀爬安全护栏，并妥善保管好个人随身物品。感谢您的理解与配合！',
      ru: 'Уважаемые гости! В целях вашей безопасности просим соблюдать указатели маршрутов, не опираться на защитные ограждения и внимательно следить за своими вещами. Благодарим за сотрудничество!',
    },
  },
  {
    id: 'closing-shuttle-service',
    title: 'Thông báo giờ đóng cửa & Chuyến xe trung chuyển cuối cùng',
    category: 'cable_car',
    categoryLabel: 'Giờ Vận Hành',
    location: 'Khu vực cổng ra & Trạm trung chuyển',
    tone: 'urgent',
    scripts: {
      vi: 'Thông báo đặc biệt: Chuyến xe trung chuyển cuối cùng trong ngày sẽ khởi hành sau 30 phút nữa tại khu vực cổng chính. Xin mời quý khách nhanh chóng di chuyển về trạm đón xe để không bị nhỡ chuyến. Đội ngũ nhân viên luôn sẵn sàng hỗ trợ quý khách. Xin cảm ơn!',
      en: 'Attention please: The last shuttle service of the day will depart in 30 minutes from the main gate station. We kindly ask all guests to proceed to the departure area to catch your ride. Our staff is available to assist you. Thank you for visiting!',
      ko: '안내 말씀 드립니다. 오늘 마지막 셔틀 버스 운행이 30분 후 메인 게이트 승강장에서 마감됩니다. 이용을 원하시는 고객께서는 서둘러 이동해 주시기 바랍니다. 감사합니다.',
      zh: '各位游客请注意：今日最后一班接驳交通班车将于30分钟后在正门发车站准时发车。请各位游客抓紧时间前往乘车，以免耽误行程。感谢您的配合！',
      ru: 'Внимание, уважаемые гости! Последний трансфер отправляется через 30 минут от главных ворот. Просим вас проследовать к месту посадки. Благодарим за посещение!',
    },
  },
  {
    id: 'lost-child-service',
    title: 'Hỗ trợ tìm người thân & Trẻ lạc',
    category: 'cskh',
    categoryLabel: 'Chăm Sóc Khách Hàng',
    location: 'Quầy thông tin & Hỗ trợ khách hàng',
    tone: 'urgent',
    scripts: {
      vi: 'Kính thưa quý khách, quầy Thông tin và Chăm sóc khách hàng hiện đang tiếp nhận một bé gái khoảng 5 tuổi, mặc váy hoa vàng, đi giày thể thao trắng đang tìm kiếm người thân. Gia đình của bé xin vui lòng liên hệ quầy thông tin gần nhất hoặc thông báo cho nhân viên bảo vệ để đón bé. Xin cảm ơn!',
      en: 'Ladies and gentlemen, our Customer Service desk is currently caring for a little girl around 5 years old, wearing a yellow floral dress and white sneakers. If you are her family, please come immediately to the nearest Customer Information Counter or contact security. Thank you.',
      ko: '안내 말씀 드립니다. 현재 고객 서비스 데스크에서 노란색 꽃무늬 원피스와 흰색 운동화를 착용한 약 5세 여자 어린이를 보호하고 있습니다. 보호자께서는 즉시 인근 안내 데스크로 와 주시기 바랍니다.',
      zh: '各位游客请注意，游客服务中心目前正暂时代为照看一名约5岁走失的小女孩，身穿黄色碎花连衣裙、白色运动鞋。如其家属听到广播，请立即前往附近的问讯处或联系工作人员认领。谢谢大家！',
      ru: 'Внимание, гости! В службе информации находится потерявшаяся девочка около 5 лет в желтом платье и белых кроссовках. Просим родителей подойти к ближайшей стойке информации. Спасибо!',
    },
  },
  {
    id: 'lost-item-bag',
    title: 'Thông báo tìm thấy tư trang / Đồ vật bỏ quên',
    category: 'cskh',
    categoryLabel: 'Chăm Sóc Khách Hàng',
    location: 'Quầy tiếp nhận đồ thất lạc',
    tone: 'standard',
    scripts: {
      vi: 'Kính thưa quý khách, nhân viên an ninh vừa tiếp nhận một chiếc túi xách màu đen bị bỏ quên tại khu vực sảnh chính. Quý khách nào làm rơi tư trang xin vui lòng mang theo giấy tờ tùy thân đến Quầy Chăm sóc khách hàng để nhận lại. Xin cảm ơn!',
      en: 'Attention please: Our security team has found a black handbag left unattended near the main lobby. If you have misplaced this item, please proceed to the Customer Service Counter with your identification to claim it. Thank you!',
      ko: '안내 말씀 드립니다. 메인 로비 구역에서 검은색 핸드백이 습득되었습니다. 분실하신 고객께서는 신분증을 지참하시고 안내 데스크로 방문해 주시기 바랍니다. 감사합니다.',
      zh: '各位游客请注意：安保人员在大厅拾获黑色手提包一个。如有失主，请持有效身份证件前往客服中心核对认领。感谢您的配合！',
      ru: 'Внимание! В главном холле найдена черная сумка. Владельца просим обратиться на стойку информации с удостоверением личности. Спасибо!',
    },
  },
];
